version: '3'
services:
  jenkins:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_GROUP_ID
    container_name: jenkins-controller
    environment:
     - JENKINS_ADMIN_ID
     - JENKINS_ADMIN_PASSWORD
     - GH_APP_KEY
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /jenkins-data:/var/jenkins_home
