credentials:
  system:
    domainCredentials:
    - credentials:
      - gitHubApp:
          appID: "145061"
          id: "github-webhooks"
          privateKey: ${GH_APP_KEY}
jenkins:
  authorizationStrategy:
    globalMatrix:
      permissions:
      - "GROUP:Overall/Administer:authenticated"
      - "USER:Job/Read:anonymous"
      - "USER:Overall/Read:anonymous"
  numExecutors: 1
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: ${JENKINS_ADMIN_ID}
        password: ${JENKINS_ADMIN_PASSWORD}
security:
  queueItemAuthenticator:
    authenticators:
    - global:
        strategy: triggeringUsersAuthorizationStrategy
jobs:
  - file: /startup/job.groovy
unclassified:
  location:
    url: https://jenkins.greatscottgadgets.com/
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
    endpoints:
    - apiUri: "https://api.github.com"
      name: "github"
  gitHubPluginConfig:
    hookUrl: "https://jenkins.greatscottgadgets.com/github-webhook/"
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
